# Xen Orchestra configuration exported by xo-apply on 2026-07-06T23:00:16.423Z
# Secrets are NOT exported: ${env:...} placeholders must be provided as environment variables.
remotes:
  - name: Synology
    type: nfs
    host: 10.100.2.23
    path: /volume1/backup
  - name: Synology1
    type: nfs
    host: 10.100.2.23
    path: /volume1/Backups
backupJobs:
  - name: Delta Backup
    mode: delta
    vms:
      raw:
        type: VM
        $pool:
          __or:
            - 751d40fa-60b5-82cf-e735-6ed42d0e03f8
        tags:
          __and:
            - __or:
                - - Backup
            - __not:
                __or:
                  - - Continuous Replication
                  - - Disaster Recovery
                  - - XOA Proxy
    remotes:
      - Synology
    settings:
      reportRecipients:
        - nick.pozza1@gmail.com
      preferNbd: true
      cbtDestroySnapshotData: true
      nbdConcurrency: 4
      backupReportTpl: compactMjml
      hideSuccessfulItems: true
      mergeBackupsSynchronously: true
      timezone: America/New_York
    schedules:
      - name: Delta Backups
        cron: 0 22 * * 1,2,3,4,5,6
        enabled: false
        timezone: America/New_York
        retention: 14
      - name: Full
        cron: 0 21 * * 0
        enabled: false
        timezone: America/New_York
        retention: 2
        settings:
          fullInterval: 1
          healthCheckSr: 4991d4aa-ed84-599b-7d19-97f2f943a366
          healthCheckVmsWithTags:
            - Health
metadataBackups:
  - name: XO Backup
    xoMetadata: true
    pools:
      - 751d40fa-60b5-82cf-e735-6ed42d0e03f8
    remotes:
      - Synology
    settings:
      reportRecipients:
        - nick.pozza1@gmail.com
      backupReportTpl: compactMjml
      hideSuccessfulItems: true
    schedules:
      - name: Daily Backup
        cron: 0 21 * * *
        enabled: false
        timezone: America/New_York
        poolRetention: 1
        xoRetention: 1
sequences:
  - name: Daily Backups
    steps:
      - job: Delta Backup
        schedule: Delta Backups
      - &a1
        job: XO Backup
        schedule: Daily Backup
    cron: 0 22 * * 1,2,3,4,5,6
    timezone: America/New_York
  - name: Full Backups
    steps:
      - job: Delta Backup
        schedule: Full
      - *a1
    cron: 0 22 * * 0
    timezone: America/New_York
users:
  - email: nick
    password: Mustang68$
    permission: admin
